modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lithereal"
version = "${version}"
displayName = "Lithereal"
authors = "Light, Alexandra"
description = '''
Lithereal is a mod about mysterious metals and crystals with magical properties that can upgrade your gear to the next level.
'''
#logoFile = ""

[[dependencies.lithereal]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"