modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="lithereal"
version="${mod_version}"
displayName="Lithereal"
logoFile="lithereal.png"
credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.lithereal]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.lithereal]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"