modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="lithereal.mixins.json"

[[mixins]]
config="lithereal-common.mixins.json"

[[mods]]
modId = "lithereal"
version = "${version}"
displayName = "Lithereal"
authors = "Light, Stunf, Alexandra"
description = '''
A mod about infusing crystals with different magical powers.
'''
#logoFile = ""

[[dependencies.lithereal]]
modId = "neoforge"
mandatory = true
versionRange = "[20.6.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "architectury"
mandatory = true
versionRange = "[12.0.28,)"
ordering = "AFTER"
side = "BOTH"