modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mixins]]
config="lithereal.mixins.json"

[[mixins]]
config="lithereal-common.mixins.json"

[[mods]]
modId = "lithereal"
version = "${version}"
displayName = "Lithereal"
authors = "Light, Alexandra"
description = '''
A mod about mysterious metals and crystals with magical properties.
'''
#logoFile = ""

[[dependencies.lithereal]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0.45-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lithereal]]
modId = "architectury"
mandatory = true
versionRange = "[12.1.4,)"
ordering = "AFTER"
side = "BOTH"